version: '2'
services:
    jhipstersample-app:
        image: jhipstersample
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstersample-postgresql:5432/jhipstersample
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersample-postgresql:
        extends:
            file: postgresql.yml
            service: jhipstersample-postgresql
